### ISSUE TITLE
Add datasets collected added to Readme

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-security-hub-v1-archive#278]
### Is your feature request related to a problem? Please describe

As a consumer of Security Hub data
I would like to be able to see what data is available to be scanned or is in the db
and that the list updates automatically in the readme (if possible)
So that, I know what has the possibility of being displayed and used by a consumer

This could look like a table in the readme with a list of things that could be pulled out of the db (Example: package size, number of critical cves...) **_Table headers_**

<img width="992" alt="Screenshot 2024-09-23 at 11 08 11 AM" src="https://github.com/user-attachments/assets/a160db29-3dd9-4c06-afd5-7ba6f92f45b4">

**Comment by benjaminwilcox** [comment]
To make sure I am understanding this ask correctly, are you asking for an example table in the readme or for there to be a real-time table in the readme?

**Comment by adam-defenseunicorns** [comment]
I think the ask is to clearly see what data is available to be queried in the db from the readme and not have to go directly into the db to find that information. Not a real time table just the data that is available. This could be in a list or in a table.
