### ISSUE TITLE
SQLite DB should only contain scan data from N-2 minor versions

### ISSUE THREAD

**Issue by koesbong** [defenseunicorns/uds-security-hub-v1-archive#285]
Currently, it looks like the SQLite data contains all historical scan data. We should make sure it only contains the Packages, Scans, and Vulnerabilities data from N-2 minor versions.

For example: if the latest version is 0.27.4, then the SQLite db should contain scan data for 0.27.4, the latest patch version from 0.26.x, and the latest patch version from 0.25.x.

Additionally, we might want to consider creating a separate DB that stores all historical scan data.

**Comment by partkyle** [comment]
After reading #225 more thoroughly, I think this could be handled by that effort.
